import React from "react";
import Image1 from '../assets/caravanImages/caravan1.jpeg'
import Image2 from '../assets/caravanImages/caravan2.jpg'
import Image3 from '../assets/caravanImages/caravan3.jpeg'
import Image4 from '../assets/caravanImages/caravan4.jpeg'
import Image5 from '../assets/caravanImages/caravan5.webp'
import Image6 from '../assets/caravanImages/caravan6.png'
import Image7 from '../assets/caravanImages/caravan7.jpg'
import Image8 from '../assets/caravanImages/caravan9.jpg'
import Image9 from '../assets/caravanImages/caravan10.jpeg'
import Image10 from '../assets/caravanImages/caravan11.webp'
import Image11 from '../assets/caravanImages/caravan12.jpeg'
import Image12 from '../assets/caravanImages/caravan13.jpeg'
import Image13 from '../assets/caravanImages/caravan14.avif'
import Image14 from '../assets/caravanImages/caravan15.jpeg'
import Image15 from '../assets/caravanImages/caravan16.jpeg'

export const CaravanData  = [
  {
    id: "2000",
    code: "ca100aa00",
    name: "Airstream Classic 30'",
    brand: "Airstream",
    cost: 250,
    year: 2023,
    ranking: 4.9,
    berths: 5,
    length: "30ft",
    location: "Seoul",
    image: Image1,
    type: "Caravan",
  },
  {
    id: "2001",
    code: "ca101bb01",
    name: "Airstream Classic 28'",
    brand: "Airstream",
    cost: 240,
    year: 2022,
    ranking: 4.8,
    berths: 4,
    length: "28ft",
    location: "Busan",
    image: Image2,
    type: "Caravan",
  },
  {
    id: "2002",
    code: "ca102cc02",
    name: "Airstream Basecamp 20'",
    brand: "Airstream",
    cost: 120,
    year: 2022,
    ranking: 4.5,
    berths: 2,
    length: "20ft",
    location: "Incheon",
    image: Image3,
    type: "Caravan",
  },
  {
    id: "2003",
    code: "ca103dd03",
    name: "Airstream Caravel 22FB",
    brand: "Airstream",
    cost: 160,
    year: 2023,
    ranking: 4.6,
    berths: 4,
    length: "22ft",
    location: "Daegu",
    image: Image4,
    type: "Caravan",
  },
  {
    id: "2004",
    code: "ca104ee04",
    name: "Airstream International 25'",
    brand: "Airstream",
    cost: 180,
    year: 2023,
    ranking: 4.7,
    berths: 4,
    length: "25ft",
    location: "Gwangju",
    image: Image5,
    type: "Caravan",
  },
  {
    id: "2005",
    code: "ca105ff05",
    name: "Adria Alpina 903 HT",
    brand: "Adria",
    cost: 220,
    year: 2021,
    ranking: 4.5,
    berths: 6,
    length: "31ft",
    location: "Daejeon",
    image: Image6,
    type: "Caravan",
  },
  {
    id: "2006",
    code: "ca106gg06",
    name: "Adria Altea 552 PK",
    brand: "Adria",
    cost: 155,
    year: 2022,
    ranking: 4.4,
    berths: 5,
    length: "24ft",
    location: "Ulsan",
    image: Image7,
    type: "Caravan",
  },
  {
    id: "2007",
    code: "ca107hh07",
    name: "Adria Action 391 LH",
    brand: "Adria",
    cost: 145,
    year: 2020,
    ranking: 4.2,
    berths: 3,
    length: "17ft",
    location: "Suwon",
    image: Image8,
    type: "Caravan",
  },
  {
    id: "2008",
    code: "ca108II08",
    name: "Hobby Excellent 490 KMF",
    brand: "Hobby",
    cost: 170,
    year: 2022,
    ranking: 4.3,
    berths: 5,
    length: "23ft",
    location: "Jeju",
    image: Image9,
    type: "Caravan",
  },
  {
    id: "2009",
    code: "ca109JJ09",
    name: "Hobby Prestige 720 UKFe",
    brand: "Hobby",
    cost: 260,
    year: 2023,
    ranking: 4.9,
    berths: 7,
    length: "29ft",
    location: "Changwon",
    image: Image10,
    type: "Caravan",
  },
  {
    id: "2010",
    code: "ca110KK10",
    name: "Bailey Phoenix 440",
    brand: "Bailey",
    cost: 130,
    year: 2021,
    ranking: 4.3,
    berths: 2,
    length: "19ft",
    location: "Goyang",
    image: Image11,
    type: "Caravan",
  },
  {
    id: "2011",
    code: "ca111LL11",
    name: "Bailey Discovery D42-4",
    brand: "Bailey",
    cost: 145,
    year: 2020,
    ranking: 4.2,
    berths: 4,
    length: "20ft",
    location: "Yongin",
    image: Image12,
    type: "Caravan",
  },
  {
    id: "2012",
    code: "ca112MM12",
    name: "Bailey Pegasus Grande Rimini",
    brand: "Bailey",
    cost: 200,
    year: 2023,
    ranking: 4.7,
    berths: 4,
    length: "25ft",
    location: "Gimpo",
    image: Image13,
    type: "Caravan",
  },
  {
    id: "2013",
    code: "ca113NN13",
    name: "Swift Sprite Super Quattro FB",
    brand: "Swift",
    cost: 220,
    year: 2022,
    ranking: 4.6,
    berths: 6,
    length: "27ft",
    location: "Pohang",
    image: Image14,
    type: "Caravan",
  },
  {
    id: "2014",
    code: "ca114OO14",
    name: "Swift Basecamp 4",
    brand: "Swift",
    cost: 135,
    year: 2021,
    ranking: 4.4,
    berths: 4,
    length: "17ft",
    location: "Guri",
    image: Image15,
    type: "Caravan",
  },
  {
    id: "2015",
    code: "ca115PP15",
    name: "Swift Challenger X 880",
    brand: "Swift",
    cost: 250,
    year: 2023,
    ranking: 4.9,
    berths: 4,
    length: "29ft",
    location: "Gunsan",
    image: Image1,
    type: "Caravan",
  },
  {
    id: "2016",
    code: "ca116QQ16",
    name: "Coachman VIP 575",
    brand: "Coachman",
    cost: 200,
    year: 2022,
    ranking: 4.7,
    berths: 4,
    length: "24ft",
    location: "Iksan",
    image: Image2,
    type: "Caravan",
  },
  {
    id: "2017",
    code: "ca117RR17",
    name: "Coachman Laser 845",
    brand: "Coachman",
    cost: 280,
    year: 2023,
    ranking: 4.9,
    berths: 5,
    length: "29ft",
    location: "Yangsan",
    image: Image3,
    type: "Caravan",
  },
  {
    id: "2018",
    code: "ca118SS18",
    name: "Coachman Acadia 460",
    brand: "Coachman",
    cost: 155,
    year: 2020,
    ranking: 4.3,
    berths: 2,
    length: "18ft",
    location: "Asan",
    image: Image4,
    type: "Caravan",
  },
  {
    id: "2019",
    code: "ca119TT19",
    name: "Elddis Affinity 550",
    brand: "Elddis",
    cost: 170,
    year: 2021,
    ranking: 4.4,
    berths: 4,
    length: "23ft",
    location: "Cheonan",
    image: Image5,
    type: "Caravan",
  },
  {
    id: "2020",
    code: "ca120UU20",
    name: "Elddis Avante 586",
    brand: "Elddis",
    cost: 220,
    year: 2022,
    ranking: 4.6,
    berths: 6,
    length: "26ft",
    location: "Mokpo",
    image: Image6,
    type: "Caravan",
  },
  {
    id: "2021",
    code: "ca121VV21",
    name: "Elddis Xplore 304",
    brand: "Elddis",
    cost: 145,
    year: 2021,
    ranking: 4.3,
    berths: 4,
    length: "18ft",
    location: "Yeosu",
    image: Image7,
    type: "Caravan",
  },
  {
    id: "2022",
    code: "ca122WW22",
    name: "Knaus Sport 500 UF",
    brand: "Knaus",
    cost: 160,
    year: 2020,
    ranking: 4.2,
    berths: 4,
    length: "23ft",
    location: "Jinju",
    image: Image8,
    type: "Caravan",
  },
  {
    id: "2023",
    code: "ca123XX23",
    name: "Knaus Sudwind 650 FSK",
    brand: "Knaus",
    cost: 280,
    year: 2023,
    ranking: 4.9,
    berths: 6,
    length: "27ft",
    location: "Gimhae",
    image: Image9,
    type: "Caravan",
  },
  {
    id: "2024",
    code: "ca124YY24",
    name: "Knaus Deseo 400 TR",
    brand: "Knaus",
    cost: 145,
    year: 2022,
    ranking: 4.4,
    berths: 2,
    length: "15ft",
    location: "Anseong",
    image: Image10,
    type: "Caravan",
  },
  {
    id: "2025",
    code: "ca125ZZ25",
    name: "Dethleffs C'Joy 410 QL",
    brand: "Dethleffs",
    cost: 133,
    year: 2020,
    ranking: 4.1,
    berths: 3,
    length: "18ft",
    location: "Gunsan",
    image: Image11,
    type: "Caravan",
  },
  {
    id: "2026",
    code: "ca126AA26",
    name: "Dethleffs Nomad 490 EST",
    brand: "Dethleffs",
    cost: 160,
    year: 2021,
    ranking: 4.5,
    berths: 4,
    length: "23ft",
    location: "Suncheon",
    image: Image12,
    type: "Caravan",
  },
  {
    id: "2027",
    code: "ca127BB27",
    name: "Dethleffs Beduin Scandinavia",
    brand: "Dethleffs",
    cost: 270,
    year: 2023,
    ranking: 4.9,
    berths: 5,
    length: "29ft",
    location: "Icheon",
    image: Image13,
    type: "Caravan",
  },
  {
    id: "2028",
    code: "ca128CC28",
    name: "Fendt Saphir 465",
    brand: "Fendt",
    cost: 145,
    year: 2021,
    ranking: 4.4,
    berths: 4,
    length: "20ft",
    location: "Andong",
    image: Image4,
    type: "Caravan",
  },
  {
    id: "2029",
    code: "ca129DD29",
    name: "Fendt Opal 515 SG",
    brand: "Fendt",
    cost: 220,
    year: 2022,
    ranking: 4.7,
    berths: 4,
    length: "24ft",
    location: "Gyeongju",
    image: Image15,
    type: "Caravan",
  },
];
