import React from "react";
import Car2Img from "../assets/CarImg1.svg";
import Car3Img from "../assets/CarImg2.svg";
import Car1Img from "../assets/CarImg3.svg";
import Car4Img from "../assets/CarImg4.svg";
import Car5Img from "../assets/CarImg5.svg";
import Car6Img from "../assets/CarImg6.svg";
import Car7Img from "../assets/CarImg7.svg";
import Car8Img from "../assets/CarImg8.svg";
import Car9Img from "../assets/CarImg9.svg";
import Car10Img from "../assets/CarImg10.svg";
import Car11Img from "../assets/CarImg11.svg";

 export const Mockdata =  [
    {
      id: "1000",
      code: "f230fh0g3",
      name: "Adventure Van",
      brand: "Hyundai",
      cost: 120,
      year: 2023,
      ranking: 4.7,
      seats: 4,
      driverLicenseType: "B",
      location: "Seoul",
      image: Car1Img,
      type: "Motor",
    },
    {
      id: "1001",
      code: "nvklal433",
      name: "Nomad Cruiser",
      brand: "Kia",
      cost: 135,
      year: 2022,
      ranking: 4.5,
      seats: 5,
      driverLicenseType: "B",
      location: "Busan",
      image: Car6Img,
      type: "Motor",
    },
    {
      id: "1002",
      code: "zz21cz3c1",
      name: "Eco Camper",
      brand: "Nissan",
      cost: 110,
      year: 2021,
      ranking: 4.2,
      seats: 2,
      driverLicenseType: "B",
      location: "Incheon",
      image: Car2Img,
      type: "Motor",
    },
    {
      id: "1003",
      code: "244wgerg2",
      name: "Family Hauler",
      brand: "Toyota",
      cost: 145,
      year: 2023,
      ranking: 4.8,
      seats: 6,
      driverLicenseType: "C",
      location: "Daegu",
      image: Car3Img,
      type: "Motor",
    },
    {
      id: "1004",
      code: "h456wer53",
      name: "Traveler X",
      brand: "Mercedes-Benz",
      cost: 180,
      year: 2024,
      ranking: 4.9,
      seats: 4,
      driverLicenseType: "C",
      location: "Daejeon",
      image: Car4Img,
      type: "Motor",
    },
    {
      id: "1005",
      code: "av2231fwg",
      name: "Camp-E",
      brand: "Tesla",
      cost: 190,
      year: 2024,
      ranking: 4.6,
      seats: 4,
      driverLicenseType: "B",
      location: "Ulsan",
      image: Car5Img,
      type: "Motor",
    },
    {
      id: "1006",
      code: "bib36pfvm",
      name: "Freedom Ride",
      brand: "Ford",
      cost: 130,
      year: 2022,
      ranking: 4.4,
      seats: 5,
      driverLicenseType: "B",
      location: "Jeonju",
      image: Car6Img,
      type: "Motor",
    },
    {
      id: "1007",
      code: "mbvjkgip5",
      name: "Skybox Van",
      brand: "Volkswagen",
      cost: 170,
      year: 2023,
      ranking: 4.7,
      seats: 4,
      driverLicenseType: "C",
      location: "Gwangju",
      image: Car7Img,
      type: "Motor",
    },
    {
      id: "1008",
      code: "vbb124btr",
      name: "Ranger Pro",
      brand: "Chevrolet",
      cost: 125,
      year: 2021,
      ranking: 4.3,
      seats: 4,
      driverLicenseType: "B",
      location: "Suwon",
      image: Car8Img,
      type: "Motor",
    },
    {
      id: "1009",
      code: "cm230f032",
      name: "Mountain Trek",
      brand: "Renault",
      cost: 140,
      year: 2022,
      ranking: 4.6,
      seats: 5,
      driverLicenseType: "B",
      location: "Gimhae",
      image: Car9Img,
      type: "Motor",
    },
    {
      id: "1010",
      code: "plb34234v",
      name: "Skywalker Van",
      brand: "Hyundai",
      cost: 115,
      year: 2021,
      ranking: 4.2,
      seats: 3,
      driverLicenseType: "B",
      location: "Chuncheon",
      image: Car10Img,
      type: "Motor",
    },
    {
      id: "1011",
      code: "4920nnc2d",
      name: "Galaxy Tourer",
      brand: "Kia",
      cost: 160,
      year: 2023,
      ranking: 4.8,
      seats: 6,
      driverLicenseType: "C",
      location: "Pohang",
      image: Car11Img,
      type: "Motor",
    },
    {
      id: "1012",
      code: "250vm23cc",
      name: "RoadStar",
      brand: "SsangYong",
      cost: 100,
      year: 2020,
      ranking: 4.0,
      seats: 2,
      driverLicenseType: "B",
      location: "Andong",
      image: Car1Img,
      type: "Motor",
    },
    {
      id: "1013",
      code: "fldsmn31b",
      name: "Ocean Nomad",
      brand: "Toyota",
      cost: 155,
      year: 2022,
      ranking: 4.5,
      seats: 5,
      driverLicenseType: "C",
      location: "Geoje",
      image: Car2Img,
      type: "Motor",
    },
    {
      id: "1014",
      code: "waas1x2as",
      name: "Offroad Titan",
      brand: "Ford",
      cost: 170,
      year: 2023,
      ranking: 4.6,
      seats: 4,
      driverLicenseType: "C",
      location: "Gwangyang",
      image: Car3Img,
      type: "Motor",
    },
    {
      id: "1015",
      code: "vb34btbg5",
      name: "Sunset Van",
      brand: "Nissan",
      cost: 125,
      year: 2021,
      ranking: 4.3,
      seats: 3,
      driverLicenseType: "B",
      location: "Yeosu",
      image: Car4Img,
      type: "Motor",
    },
    {
      id: "1016",
      code: "k8l6j58jl",
      name: "Mini Nomad",
      brand: "Hyundai",
      cost: 95,
      year: 2020,
      ranking: 4.1,
      seats: 2,
      driverLicenseType: "B",
      location: "Gangneung",
      image: Car5Img,
      type: "Motor",
    },
    {
      id: "1017",
      code: "v435nn85n",
      name: "Dream Camper",
      brand: "Kia",
      cost: 150,
      year: 2023,
      ranking: 4.7,
      seats: 5,
      driverLicenseType: "B",
      location: "Cheongju",
      image: Car6Img,
      type: "Motor",
    },
    {
      id: "1018",
      code: "09zx9c0zc",
      name: "Ultimate Ride",
      brand: "Mercedes-Benz",
      cost: 200,
      year: 2024,
      ranking: 5.0,
      seats: 4,
      driverLicenseType: "C",
      location: "Sejong",
      image: Car7Img,
      type: "Motor",
    },
    {
      id: "1019",
      code: "mnb5mb2m5",
      name: "Nature Roamer",
      brand: "Renault",
      cost: 130,
      year: 2022,
      ranking: 4.4,
      seats: 4,
      driverLicenseType: "B",
      location: "Uijeongbu",
      image: Car8Img,
      type: "Motor",
    },
    {
      id: "1020",
      code: "r23fwf2w3",
      name: "Backcountry Beast",
      brand: "Ford",
      cost: 165,
      year: 2023,
      ranking: 4.6,
      seats: 4,
      driverLicenseType: "C",
      location: "Mokpo",
      image: Car9Img,
      type: "Motor",
    },
    {
      id: "1021",
      code: "pxpzczo23",
      name: "City Cruiser",
      brand: "Volkswagen",
      cost: 145,
      year: 2022,
      ranking: 4.5,
      seats: 5,
      driverLicenseType: "B",
      location: "Anyang",
      image: Car10Img,
      type: "Motor",
    },
    {
      id: "1022",
      code: "2c42cb5cb",
      name: "Wave Rider",
      brand: "Chevrolet",
      cost: 130,
      year: 2021,
      ranking: 4.3,
      seats: 3,
      driverLicenseType: "B",
      location: "Goyang",
      image: Car11Img,
      type: "Motor",
    },
    {
      id: "1023",
      code: "5k43kkk23",
      name: "Freedom Mini",
      brand: "Hyundai",
      cost: 105,
      year: 2020,
      ranking: 4.2,
      seats: 2,
      driverLicenseType: "B",
      location: "Jeju",
      image: Car1Img,
      type: "Motor",
    },
    {
      id: "1024",
      code: "lm2tny2k4",
      name: "Alpine Express",
      brand: "Kia",
      cost: 150,
      year: 2023,
      ranking: 4.8,
      seats: 5,
      driverLicenseType: "C",
      location: "Gumi",
      image: Car2Img,
      type: "Motor",
    },
    {
      id: "1025",
      code: "nbm5mv45n",
      name: "Comfy Camper",
      brand: "Nissan",
      cost: 115,
      year: 2021,
      ranking: 4.2,
      seats: 3,
      driverLicenseType: "B",
      location: "Seosan",
      image: Car3Img,
      type: "Motor",
    },
    {
      id: "1026",
      code: "zx23zc42c",
      name: "Power Wagon",
      brand: "SsangYong",
      cost: 130,
      year: 2022,
      ranking: 4.4,
      seats: 4,
      driverLicenseType: "B",
      location: "Suncheon",
      image: Car4Img,
      type: "Motor",
    },
    {
      id: "1027",
      code: "acvx872gc",
      name: "Explorer Max",
      brand: "Toyota",
      cost: 160,
      year: 2023,
      ranking: 4.7,
      seats: 6,
      driverLicenseType: "C",
      location: "Changwon",
      image: Car5Img,
      type: "Motor",
    },
    {
      id: "1028",
      code: "tx125ck42",
      name: "Night Nomad",
      brand: "Volkswagen",
      cost: 140,
      year: 2022,
      ranking: 4.5,
      seats: 4,
      driverLicenseType: "B",
      location: "Iksan",
      image: Car6Img,
      type: "Motor",
    },
    {
      id: "1029",
      code: "gwuby345v",
      name: "Hybrid Trek",
      brand: "Tesla",
      cost: 185,
      year: 2023,
      seats: 4,
      driverLicenseType: "B",
      location: "Paju",
      image: Car7Img,
      type: "Motor",
    },
  ];


