import React from "react";
import CarUsed1 from '../assets/usedCar/usedCar1.jpeg'
import CarUsed2 from '../assets/usedCar/usedCar2.webp'
import CarUsed3 from '../assets/usedCar/usedCar3.jpeg'
import CarUsed4 from '../assets/usedCar/usedCar4.jpeg'
import CarUsed5 from '../assets/usedCar/usedCar5.jpg'
import CarUsed6 from '../assets/usedCar/usedCar6.jpg'
import CarUsed7 from '../assets/usedCar/usedCar7.png'
import CarUsed8 from '../assets/usedCar/usedCar8.jpg'
import CarUsed9 from '../assets/usedCar/usedCar9.jpeg'
import CarUsed10 from '../assets/usedCar/usedCar10.jpeg'
import CarUsed11 from '../assets/usedCar/usedCar11.jpeg'
import CarUsed12 from '../assets/usedCar/usedCar12.jpg'
import CarUsed13 from '../assets/usedCar/usedCar13.jpg'
import CarUsed14 from '../assets/usedCar/usedCar14.jpg'
import CarUsed15 from '../assets/usedCar/usedCar15.webp'

export const UsedCarData = [
  {
    id: "5000",
    code: "used100xa1",
    name: "Ocean Cruiser Classic",
    brand: "Hyundai",
    cost: 100,
    year: 2017,
    ranking: 4.5,
    seats: 4,
    driverLicenseType: "B",
    location: "Seoul",
    image: CarUsed1,
    type: "Used Cars",
  },
  {
    id: "5001",
    code: "used101xa2",
    name: "Wildland Legacy",
    brand: "Ford",
    cost: 95,
    year: 2016,
    ranking: 4.2,
    seats: 5,
    driverLicenseType: "B",
    location: "Busan",
     image: CarUsed2,
     type: "Used Cars",
  },
  {
    id: "5002",
    code: "used102xa3",
    name: "Nightstar Retro",
    brand: "Peugeot",
    cost: 80,
    year: 2015,
    ranking: 4.0,
    seats: 4,
    driverLicenseType: "B",
    location: "Incheon",
     image: CarUsed3,
     type: "Used Cars",
  },
  {
    id: "5003",
    code: "used103xa4",
    name: "Expedition Legacy",
    brand: "Nissan",
    cost: 120,
    year: 2017,
    ranking: 4.6,
    seats: 6,
    driverLicenseType: "C",
    location: "Daegu",
     image: CarUsed4,
     type: "Used Cars",
  },
  {
    id: "5004",
    code: "used104xa5",
    name: "Alpine Rush Old",
    brand: "Volkswagen",
    cost: 90,
    year: 2015,
    ranking: 4.1,
    seats: 3,
    driverLicenseType: "B",
    location: "Daejeon",
     image: CarUsed5,
     type: "Used Cars",
  },
  {
    id: "5005",
    code: "used105xa6",
    name: "Road King Legacy",
    brand: "Chevrolet",
    type: "Used Cars",
    cost: 130,
    year: 2017,
    ranking: 4.5,
    seats: 5,
    driverLicenseType: "B",
    location: "Gwangju",
     image: CarUsed6,
  },
  {
    id: "5006",
    code: "used106xa7",
    name: "Forest Quest 2015",
    brand: "Renault",
    cost: 79,
    year: 2015,
    ranking: 4.0,
    seats: 4,
    driverLicenseType: "B",
    location: "Ulsan",
     image: CarUsed7,
     type: "Used Cars",
  },
  {
    id: "5007",
    code: "used107xa8",
    name: "Basecamp Legacy",
    brand: "Fiat",
    cost: 85,
    year: 2016,
    ranking: 4.2,
    seats: 4,
    driverLicenseType: "B",
    location: "Gimhae",
     image: CarUsed8,
     type: "Used Cars",
  },
  {
    id: "5008",
    code: "used108xa9",
    name: "Sunset Escape Old",
    brand: "Peugeot",
    cost: 79,
    year: 2015,
    ranking: 4.0,
    seats: 2,
    driverLicenseType: "B",
    location: "Jeju",
     image: CarUsed9,
     type: "Used Cars",
  },
  {
    id: "5009",
    code: "used109xa0",
    name: "Pathfinder Legacy",
    brand: "Mazda",
    cost: 95,
    year: 2017,
    ranking: 4.3,
    seats: 4,
    driverLicenseType: "B",
    location: "Suwon",
     image: CarUsed10,
     type: "Used Cars",
  },
  {
    id: "5010",
    code: "used110xb1",
    name: "Rover Quest 2016",
    brand: "Hyundai",
    cost: 100,
    year: 2016,
    ranking: 4.4,
    seats: 5,
    driverLicenseType: "B",
    location: "Goyang",
     image: CarUsed11,
     type: "Used Cars",
  },
  {
    id: "5011",
    code: "used111xb2",
    name: "Custom Horizon 2015",
    brand: "Ford",
    cost: 140,
    year: 2015,
    ranking: 4.5,
    seats: 6,
    driverLicenseType: "C",
    location: "Jinju",
     image: CarUsed12,
     type: "Used Cars",
  },
  {
    id: "5012",
    code: "used112xb3",
    name: "Urban Nomad 2016",
    brand: "Citroën",
    cost: 79,
    year: 2016,
    ranking: 4.1,
    seats: 4,
    driverLicenseType: "B",
    location: "Asan",
     image: CarUsed13,
     type: "Used Cars",
  },
  {
    id: "5013",
    code: "used113xb4",
    name: "Highland Haven Old",
    brand: "Peugeot",
    cost: 95,
    year: 2017,
    ranking: 4.2,
    seats: 5,
    driverLicenseType: "B",
    location: "Guri",
     image: CarUsed14,
     type: "Used Cars",
  },
  {
    id: "5014",
    code: "used114xb5",
    name: "Prairie Eagle 2015",
    brand: "Mazda",
    cost: 100,
    year: 2015,
    ranking: 4.3,
    seats: 4,
    driverLicenseType: "B",
    location: "Andong",
     image: CarUsed15,
     type: "Used Cars",
  },
  {
    id: "5015",
    code: "used115xb6",
    name: "Scenic Drift Old",
    brand: "Fiat",
    cost: 79,
    year: 2015,
    ranking: 4.0,
    seats: 2,
    driverLicenseType: "B",
    location: "Gunsan",
     image: CarUsed10,
     type: "Used Cars",
  },
];
