const CampingCars = [
  {
    id: 1,
    name: "Adventure Van",
    brand: "Hyundai",
    cost: 120,
    year: 2023,
    ranking: 4.7,
    seats: 4,
    driverLicenseType: "B",
    location: "Seoul",
  },
  {
    id: 2,
    name: "Nomad Cruiser",
    brand: "Kia",
    cost: 135,
    year: 2022,
    ranking: 4.5,
    seats: 5,
    driverLicenseType: "B",
    location: "Busan",
  },
  {
    id: 3,
    name: "Eco Camper",
    brand: "Nissan",
    cost: 110,
    year: 2021,
    ranking: 4.2,
    seats: 2,
    driverLicenseType: "B",
    location: "Incheon",
  },
  {
    id: 4,
    name: "Family Hauler",
    brand: "Toyota",
    cost: 145,
    year: 2023,
    ranking: 4.8,
    seats: 6,
    driverLicenseType: "C",
    location: "Daegu",
  },
  {
    id: 5,
    name: "Traveler X",
    brand: "Mercedes-Benz",
    cost: 180,
    year: 2024,
    ranking: 4.9,
    seats: 4,
    driverLicenseType: "C",
    location: "Daejeon",
  },
  {
    id: 6,
    name: "Camp-E",
    brand: "Tesla",
    cost: 190,
    year: 2024,
    ranking: 4.6,
    seats: 4,
    driverLicenseType: "B",
    location: "Ulsan",
  },
  {
    id: 7,
    name: "Freedom Ride",
    brand: "Ford",
    cost: 130,
    year: 2022,
    ranking: 4.4,
    seats: 5,
    driverLicenseType: "B",
    location: "Jeonju",
  },
  {
    id: 8,
    name: "Skybox Van",
    brand: "Volkswagen",
    cost: 170,
    year: 2023,
    ranking: 4.7,
    seats: 4,
    driverLicenseType: "C",
    location: "Gwangju",
  },
  {
    id: 9,
    name: "Ranger Pro",
    brand: "Chevrolet",
    cost: 125,
    year: 2021,
    ranking: 4.3,
    seats: 4,
    driverLicenseType: "B",
    location: "Suwon",
  },
  {
    id: 10,
    name: "Mountain Trek",
    brand: "Renault",
    cost: 140,
    year: 2022,
    ranking: 4.6,
    seats: 5,
    driverLicenseType: "B",
    location: "Gimhae",
  },
  {
    id: 11,
    name: "Skywalker Van",
    brand: "Hyundai",
    cost: 115,
    year: 2021,
    ranking: 4.2,
    seats: 3,
    driverLicenseType: "B",
    location: "Chuncheon",
  },
  {
    id: 12,
    name: "Galaxy Tourer",
    brand: "Kia",
    cost: 160,
    year: 2023,
    ranking: 4.8,
    seats: 6,
    driverLicenseType: "C",
    location: "Pohang",
  },
  {
    id: 13,
    name: "RoadStar",
    brand: "SsangYong",
    cost: 100,
    year: 2020,
    ranking: 4.0,
    seats: 2,
    driverLicenseType: "B",
    location: "Andong",
  },
  {
    id: 14,
    name: "Ocean Nomad",
    brand: "Toyota",
    cost: 155,
    year: 2022,
    ranking: 4.5,
    seats: 5,
    driverLicenseType: "C",
    location: "Geoje",
  },
  {
    id: 15,
    name: "Offroad Titan",
    brand: "Ford",
    cost: 170,
    year: 2023,
    ranking: 4.6,
    seats: 4,
    driverLicenseType: "C",
    location: "Gwangyang",
  },
  {
    id: 16,
    name: "Sunset Van",
    brand: "Nissan",
    cost: 125,
    year: 2021,
    ranking: 4.3,
    seats: 3,
    driverLicenseType: "B",
    location: "Yeosu",
  },
  {
    id: 17,
    name: "Mini Nomad",
    brand: "Hyundai",
    cost: 95,
    year: 2020,
    ranking: 4.1,
    seats: 2,
    driverLicenseType: "B",
    location: "Gangneung",
  },
  {
    id: 18,
    name: "Dream Camper",
    brand: "Kia",
    cost: 150,
    year: 2023,
    ranking: 4.7,
    seats: 5,
    driverLicenseType: "B",
    location: "Cheongju",
  },
  {
    id: 19,
    name: "Ultimate Ride",
    brand: "Mercedes-Benz",
    cost: 200,
    year: 2024,
    ranking: 5.0,
    seats: 4,
    driverLicenseType: "C",
    location: "Sejong",
  },
  {
    id: 20,
    name: "Nature Roamer",
    brand: "Renault",
    cost: 130,
    year: 2022,
    ranking: 4.4,
    seats: 4,
    driverLicenseType: "B",
    location: "Uijeongbu",
  },
  {
    id: 21,
    name: "Backcountry Beast",
    brand: "Ford",
    cost: 165,
    year: 2023,
    ranking: 4.6,
    seats: 4,
    driverLicenseType: "C",
    location: "Mokpo",
  },
  {
    id: 22,
    name: "City Cruiser",
    brand: "Volkswagen",
    cost: 145,
    year: 2022,
    ranking: 4.5,
    seats: 5,
    driverLicenseType: "B",
    location: "Anyang",
  },
  {
    id: 23,
    name: "Wave Rider",
    brand: "Chevrolet",
    cost: 130,
    year: 2021,
    ranking: 4.3,
    seats: 3,
    driverLicenseType: "B",
    location: "Goyang",
  },
  {
    id: 24,
    name: "Freedom Mini",
    brand: "Hyundai",
    cost: 105,
    year: 2020,
    ranking: 4.2,
    seats: 2,
    driverLicenseType: "B",
    location: "Jeju",
  },
  {
    id: 25,
    name: "Alpine Express",
    brand: "Kia",
    cost: 150,
    year: 2023,
    ranking: 4.8,
    seats: 5,
    driverLicenseType: "C",
    location: "Gumi",
  },
  {
    id: 26,
    name: "Comfy Camper",
    brand: "Nissan",
    cost: 115,
    year: 2021,
    ranking: 4.2,
    seats: 3,
    driverLicenseType: "B",
    location: "Seosan",
  },
  {
    id: 27,
    name: "Power Wagon",
    brand: "SsangYong",
    cost: 130,
    year: 2022,
    ranking: 4.4,
    seats: 4,
    driverLicenseType: "B",
    location: "Suncheon",
  },
  {
    id: 28,
    name: "Explorer Max",
    brand: "Toyota",
    cost: 160,
    year: 2023,
    ranking: 4.7,
    seats: 6,
    driverLicenseType: "C",
    location: "Changwon",
  },
  {
    id: 29,
    name: "Night Nomad",
    brand: "Volkswagen",
    cost: 140,
    year: 2022,
    ranking: 4.5,
    seats: 4,
    driverLicenseType: "B",
    location: "Iksan",
  },
  {
    id: 30,
    name: "Hybrid Trek",
    brand: "Tesla",
    cost: 185,
    year: 2024,
    ranking: 4.9,
    seats: 4,
    driverLicenseType: "B",
    location: "Paju",
  },
];

export default CampingCars;
