import React from "react";
import Tuning1 from '../assets/tuningImages/tuned1.jpeg'
import Tuning2 from '../assets/tuningImages/tuned2.jpeg'
import Tuning3 from '../assets/tuningImages/tuned3.jpeg'
import Tuning4 from '../assets/tuningImages/tuned4.jpeg'
import Tuning5 from '../assets/tuningImages/tuned5.jpeg'
import Tuning6 from '../assets/tuningImages/tuned6.jpeg'
import Tuning7 from '../assets/tuningImages/tuned7.jpeg'
import Tuning8 from '../assets/tuningImages/tuned8.jpeg'
import Tuning9 from '../assets/tuningImages/tuned9.jpeg'
import Tuning10 from '../assets/tuningImages/tuned10.jpeg'
import Tuning11 from '../assets/tuningImages/tuned11.jpeg'
import Tuning12 from '../assets/tuningImages/tuned12.jpeg'
import Tuning13 from '../assets/tuningImages/tuned13.jpeg'
import Tuning14 from '../assets/tuningImages/tuned14.jpeg'
import Tuning15 from '../assets/tuningImages/tuned15.jpeg'

export const TuningData = [
  {
    id: "4000",
    code: "tun100xa1",
    name: "Ocean Cruiser X",
    brand: "Mercedes-Benz",
    cost: 220,
    year: 2023,
    ranking: 4.9,
    seats: 4,
    driverLicenseType: "B",
    location: "Seoul",
    image: Tuning1,
  },
  {
    id: "4001",
    code: "tun101xa2",
    name: "Wildland Warrior",
    brand: "Ford",
    cost: 250,
    year: 2022,
    ranking: 4.7,
    seats: 5,
    driverLicenseType: "B",
    location: "Busan",
    image: Tuning2,
  },
  {
    id: "4002",
    code: "tun102xa3",
    name: "Nightstar Cruiser",
    brand: "Hyundai",
    cost: 200,
    year: 2021,
    ranking: 4.6,
    seats: 4,
    driverLicenseType: "B",
    location: "Incheon",
    image: Tuning3,
  },
  {
    id: "4003",
    code: "tun103xa4",
    name: "Expedition MaxX",
    brand: "Nissan",
    cost: 280,
    year: 2023,
    ranking: 4.9,
    seats: 6,
    driverLicenseType: "C",
    location: "Daegu",
    image: Tuning4,
  },
  {
    id: "4004",
    code: "tun104xa5",
    name: "Alpine Rush",
    brand: "Volkswagen",
    cost: 160,
    year: 2021,
    ranking: 4.3,
    seats: 3,
    driverLicenseType: "B",
    location: "Daejeon",
    image: Tuning5,
  },
  {
    id: "4005",
    code: "tun105xa6",
    name: "Road King XL",
    brand: "Chevrolet",
    cost: 245,
    year: 2022,
    ranking: 4.7,
    seats: 5,
    driverLicenseType: "B",
    location: "Gwangju",
    image: Tuning6,
  },
  {
    id: "4006",
    code: "tun106xa7",
    name: "Forest Quest",
    brand: "Renault",
    cost: 135,
    year: 2021,
    ranking: 4.4,
    seats: 4,
    driverLicenseType: "B",
    location: "Ulsan",
    image: Tuning7,
  },
  {
    id: "4007",
    code: "tun107xa8",
    name: "Basecamp Master",
    brand: "Fiat",
    cost: 155,
    year: 2022,
    ranking: 4.5,
    seats: 4,
    driverLicenseType: "B",
    location: "Gimhae",
    image: Tuning8,
  },
  {
    id: "4008",
    code: "tun108xa9",
    name: "Sunset Escape",
    brand: "Peugeot",
    cost: 145,
    year: 2021,
    ranking: 4.3,
    seats: 2,
    driverLicenseType: "B",
    location: "Jeju",
    image: Tuning9,
  },
  {
    id: "4009",
    code: "tun109xa0",
    name: "Pathfinder PRO",
    brand: "Mazda",
    cost: 235,
    year: 2023,
    ranking: 4.9,
    seats: 4,
    driverLicenseType: "B",
    location: "Suwon",
    image: Tuning10,
  },
  {
    id: "4010",
    code: "tun110xb1",
    name: "Rover Quest",
    brand: "Hyundai",
    cost: 169,
    year: 2022,
    ranking: 4.5,
    seats: 5,
    driverLicenseType: "B",
    location: "Goyang",
    image: Tuning11,
  },
  {
    id: "4011",
    code: "tun111xb2",
    name: "Custom Horizon",
    brand: "Ford",
    cost: 289,
    year: 2023,
    ranking: 4.9,
    seats: 6,
    driverLicenseType: "C",
    location: "Jinju",
    image: Tuning12,
  },
  {
    id: "4012",
    code: "tun112xb3",
    name: "Urban Nomad",
    brand: "Citroën",
    cost: 155,
    year: 2021,
    ranking: 4.4,
    seats: 4,
    driverLicenseType: "B",
    location: "Asan",
    image: Tuning13,
  },
  {
    id: "4013",
    code: "tun113xb4",
    name: "Highland Haven",
    brand: "Peugeot",
    cost: 160,
    year: 2022,
    ranking: 4.5,
    seats: 5,
    driverLicenseType: "B",
    location: "Guri",
    image: Tuning14,
  },
  {
    id: "4014",
    code: "tun114xb5",
    name: "Prairie Eagle",
    brand: "Mazda",
    cost: 220,
    year: 2023,
    ranking: 4.7,
    seats: 4,
    driverLicenseType: "B",
    location: "Andong",
    image: Tuning15,
  },
  {
    id: "4015",
    code: "tun115xb6",
    name: "Scenic Drift",
    brand: "Fiat",
    cost: 135,
    year: 2021,
    ranking: 4.2,
    seats: 2,
    driverLicenseType: "B",
    location: "Gunsan",
    image: Tuning1,
  },
  {
    id: "4016",
    code: "tun116xb7",
    name: "Blackwood Expedition",
    brand: "Hyundai",
    cost: 250,
    year: 2022,
    ranking: 4.7,
    seats: 6,
    driverLicenseType: "C",
    location: "Suncheon",
    image: Tuning2,
  },
  {
    id: "4017",
    code: "tun117xb8",
    name: "Aurora Quest",
    brand: "Nissan",
    cost: 200,
    year: 2023,
    ranking: 4.9,
    seats: 4,
    driverLicenseType: "B",
    location: "Gyeongju",
    image: Tuning3,
  },
  {
    id: "4018",
    code: "tun118xb9",
    name: "Drifter Pro",
    brand: "Mazda",
    cost: 145,
    year: 2021,
    ranking: 4.3,
    seats: 2,
    driverLicenseType: "B",
    location: "Gimpo",
    image: Tuning4,
  },
  {
    id: "4019",
    code: "tun119xb0",
    name: "Atlas Rush",
    brand: "Renault",
    cost: 175,
    year: 2022,
    ranking: 4.6,
    seats: 4,
    driverLicenseType: "B",
    location: "Gwangyang",
    image: Tuning5,
  },
  {
    id: "4020",
    code: "tun120xb1",
    name: "Epic Venture",
    brand: "Chevrolet",
    cost: 245,
    year: 2023,
    ranking: 4.9,
    seats: 6,
    driverLicenseType: "C",
    location: "Gimcheon",
    image: Tuning6,
  },
  {
    id: "4021",
    code: "tun121xb2",
    name: "Pulse Quest",
    brand: "Peugeot",
    cost: 160,
    year: 2021,
    ranking: 4.5,
    seats: 4,
    driverLicenseType: "B",
    location: "Mokpo",
    image: Tuning7,
  },
  {
    id: "4022",
    code: "tun122xb3",
    name: "Backroads King",
    brand: "Mazda",
    cost: 220,
    year: 2022,
    ranking: 4.7,
    seats: 5,
    driverLicenseType: "B",
    location: "Yangsan",
    image: Tuning8,
  },
  {
    id: "4023",
    code: "tun123xb4",
    name: "Custom Heights",
    brand: "Hyundai",
    cost: 289,
    year: 2023,
    ranking: 4.9,
    seats: 6,
    driverLicenseType: "C",
    location: "Namyangju",
    image: Tuning9,
  },
  {
    id: "4024",
    code: "tun124xb5",
    name: "Trend Quest",
    brand: "Fiat",
    cost: 155,
    year: 2021,
    ranking: 4.4,
    seats: 4,
    driverLicenseType: "B",
    location: "Pyeongtaek",
    image: Tuning10,
  },
  {
    id: "4025",
    code: "tun125xb6",
    name: "Ocean Heights XL",
    brand: "Nissan",
    cost: 220,
    year: 2022,
    ranking: 4.7,
    seats: 5,
    driverLicenseType: "B",
    location: "Iksan",
    image: Tuning11,
  },
  {
    id: "4026",
    code: "tun126xb7",
    name: "Expanse Glide",
    brand: "Mazda",
    cost: 145,
    year: 2021,
    ranking: 4.3,
    seats: 2,
    driverLicenseType: "B",
    location: "Jecheon",
    image: Tuning12,
  },
  {
    id: "4027",
    code: "tun127xb8",
    name: "Proline Bushmaster",
    brand: "Hyundai",
    cost: 289,
    year: 2023,
    ranking: 4.9,
    seats: 6,
    driverLicenseType: "C",
    location: "Wonju",
    image: Tuning13,
  },
  {
    id: "4028",
    code: "tun128xb9",
    name: "Comet Quest",
    brand: "Peugeot",
    cost: 160,
    year: 2022,
    ranking: 4.5,
    seats: 4,
    driverLicenseType: "B",
    location: "Nonsan",
    image: Tuning14,
  },
  {
    id: "4029",
    code: "tun129xb0",
    name: "Highroad Warrior",
    brand: "Mazda",
    cost: 220,
    year: 2023,
    ranking: 4.7,
    seats: 5,
    driverLicenseType: "B",
    location: "Gunsan",
    image: Tuning15,
  },
];
